# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_produccion', '0007_auto_20160623_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date_created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_machine',
        ),
        migrations.RemoveField(
            model_name='order_process',
            name='order_process_datetime_finished',
        ),
        migrations.RemoveField(
            model_name='order_process',
            name='order_process_datetime_pause_start',
        ),
        migrations.RemoveField(
            model_name='order_process',
            name='order_process_datetime_started',
        ),
        migrations.RemoveField(
            model_name='order_process',
            name='order_process_is_paused',
        ),
        migrations.RemoveField(
            model_name='order_process',
            name='order_process_seconds_paused',
        ),
        migrations.RemoveField(
            model_name='order_process',
            name='order_process_user_finished',
        ),
        migrations.RemoveField(
            model_name='order_process',
            name='order_process_user_started',
        ),
        migrations.AddField(
            model_name='order',
            name='order_sh_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='process_group_sh_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='process_sh_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
