# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_produccion', '0010_auto_20160809_1435'),
    ]
