# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_produccion', '0011_auto_20160809_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_group',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_produccion.Group', to_field='group_sh_id'),
        ),
    ]
