# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_produccion', '0012_auto_20160809_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='process_group_name',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='process_group_sh_id',
            new_name='group_sh_id',
        ),
    ]
