# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_produccion', '0014_auto_20160809_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_process_is_started', models.BooleanField(default=False)),
                ('order_process_is_finished', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_produccion.Order')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_produccion.Process')),
            ],
        ),
        migrations.RemoveField(
            model_name='group_process',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group_process',
            name='process',
        ),
        migrations.RemoveField(
            model_name='group',
            name='processes',
        ),
        migrations.DeleteModel(
            name='Group_Process',
        ),
        migrations.AddField(
            model_name='order',
            name='processes',
            field=models.ManyToManyField(through='control_produccion.Order_Process', to='control_produccion.Process'),
        ),
    ]
