# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_produccion', '0016_order_order_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
