# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_produccion', '0018_process_group_sh_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_product_number',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_op_number',
            field=models.CharField(max_length=10),
        ),
    ]
